### ISSUE TITLE
BUG记录-20211104

### ISSUE THREAD

**Issue by EagleZhou96** [OneEyedEagle/EAGLE-RGSS3#1]
【能力学习系统】
在调用reset时，将当前选中的token进行保存，防止底部按键提示出现闪烁重绘

【对话日志】
在录入对话框扩展的name时，未处理它自带的修改后的\e<id>类型的转义符

**Comment by OneEyedEagle** [comment]
【能力学习系统】
由于reset时全部token重新绘制，无法保留原有信息，即token精灵不再是同一个，暂时放弃

【对话日志】
已经兼容对话框扩展的姓名框的转义符
